name: ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
jobs:
  test:
    strategy:
      matrix:
        deno-version: [v1.x]
        os: [macos-latest, ubuntu-latest]
    name: deno lint and test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: run lint
        run: deno lint
      - name: run test
        run: deno test --allow-env
